[package]
name = "kilit-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
base64 = "0.13"
clap = "3.0"
rustyline = "12"
rpassword = "7"
rand = "0.9.0"